name: Deploy to EC2 (Sandri-BE)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Prepare SSH key
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 600 key.pem
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd ~/Sandri-BE

          echo "ðŸ“Œ Pulling latest source..."
          git pull origin main

          echo " Building application..."
          ./gradlew clean build -x test

          echo "ðŸ›‘ Stopping previous app if running..."
          pids=$(pgrep -f "Sandri-BE")
          i
